language: node_js
node_js:
  - "8"

branches:
  only:
    - master

install:
  - npm install -g firebase-tools
  - npm install --prefix ./functions

script:
  - npm test --prefix ./functions

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT --only functions