language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - cd functions && npm install

script:
  - cd functions && npm test

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT --only functions