language: node_js
node_js:
  - "8"

branches:
  only:
    - master

install:
  - npm install -g firebase-tools
  - npm install --prefix ./functions
  - npm tsc --version

script:
  - npm test --prefix ./functions
  - firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT --only functions

after_success:
  - echo "Done Done Done Done!!!"
  